#
# File:    ./pyproject.toml
# Author:  Jiří Kučera <sanczes AT gmail.com>
# Date:    2021-03-12 15:02:40 +0100
# Project: testlab: Testing laboratory
# Brief:   Configuration for python linters
#
# SPDX-License-Identifier: MIT
#

[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79

[tool.pylint.design]
min-public-methods = 0

[tool.pylint.format]
max-line-length = 79

[tool.pylint."message control"]
# Disable not PEP 8 compliant warnings:
#   C0330: Wrong hanging indentation before block (add 4 spaces)
#   C0326: Bad whitespace
#   E0401: Unable to import ... (import-error)
#   W0212: Access to a protected member ... (protected-access)
disable = ["C0330", "C0326", "E0401", "W0212"]
